#index:
#    path: /
#    controller: App\Controller\DefaultController::index
logout:
  path: /logout


gregwar_captcha_routing:
  resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
  prefix: /_gcb
