<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTKqB6dO\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTKqB6dO/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTKqB6dO.legacy');
if (\class_exists(\ContainerZQ5BBAv\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZQ5BBAv/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZQ5BBAv.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTKqB6dO\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTKqB6dO\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'TKqB6dO',
    'container.build_id' => 'd9e0464a',
    'container.build_time' => 1620145972,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTKqB6dO');
    \class_alias(\ContainerZQ5BBAv\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZQ5BBAv\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZQ5BBAv',
    'container.build_id' => '7d908848',
    'container.build_time' => 1620104723,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZQ5BBAv');
