<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA7rYzzE\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA7rYzzE/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA7rYzzE.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA7rYzzE\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerA7rYzzE\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'A7rYzzE',
    'container.build_id' => 'e203957d',
    'container.build_time' => 1620094136,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA7rYzzE');
